### 회원가입
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "name": "minsoo",
  "email": "choi@gmail.com",
  "phoneNumber": "01011112222",
  "password": "1234",
  "type": "GENERAL"
}

### 회원가입 - 멤버2
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "name": "ms",
  "email": "ms@gmail.com",
  "password": "5678"
}

### 회원가입 - 멤버3
POST {{baseUrl}}/auth/signUp
Content-Type: application/json

{
  "name": "third",
  "email": "3@gmail.com",
  "password": "5678"
}

#### 로그인
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "general@gmail.com",
  "password": "qqq",
  "type": "GENERAL"
}
